### PR TITLE
WIP: phpcpd task

### PR DESCRIPTION
**Pull request by tombevers**
Adding a phpcpd task

### CODE REVIEW

**Comment by veewee** [comment]
What is the state on this PR?

**Comment by tombevers** [comment]
Didn't had time to pick it up again but I was working on excluding the spec and test dir by default.

**Comment by veewee** [comment]
@tombevers Are you planning to finish this PR any time soon? Thanks!

**Comment by veewee** [comment]
Closed in favour of #195.

**Pull request closed without merging**
