### PR TITLE
Implement the Phpcs exclude option

### PR DESCRIPTION
**Pull request by JTubex**
| Q             | A
| ------------- | ---
| Branch        | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Documented?   | yes

Add the exclude option to the phpcs-task: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#limiting-results-to-specific-sniffs

### CODE REVIEW

**Comment by JTubex** [comment]
Hmm, tests are failing because of the following error:
`1) GrumPHPTest\E2E\FolderStructuresTest::it_has_all_config_files_in_root_git_dir
320Symfony\Component\Process\Exception\ProcessTimedOutException: The process "c:\tools\php71\php.EXE C:\tools\composer install --optimize-autoloader --no-interaction" exceeded the timeout of 60 seconds.`

**Comment by veewee** [comment]
Looks good, thanks for the PR!

**Comment by oallain** [comment]
Good job !

**Comment by JTubex** [comment]
Thanks, guys!

**Pull request merged**
