### PR TITLE
Added coloured ballot marks for completed tasks.

### PR DESCRIPTION
**Pull request by Bilge**
| Q             | A
| ------------- | ---
| Branch        | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Documented?   | no
| Fixed tickets | n/a

It would be nice to get an overview of which tasks passed and failed while GrumPHP is executing. Tasks that complete successfully tend to not output anything which isn't very helpful. Now tasks will output either a green ✔ or red ✘ in the progress summary.

### CODE REVIEW

**Comment by veewee** [comment]
The formatting for skipped tasks doesn't seem right:
https://ci.appveyor.com/project/veewee/grumphp/build/job/9dmtvi4m2blh9rdd

Can every cli environment handle these special characters?

**Comment by Bilge** [comment]
>Can every cli environment handle these special characters?

If that wasn't an issue when you decided to paste a grumpy old man into people's consoles I don't see why it would be an issue now.

**Comment by veewee** [comment]
It was way to early on a friday to do review :)

**Comment by Bilge** [comment]
@veewee It seems you will need to manually restart the AppVeyor builds.

**Pull request merged**
