### PR TITLE
Create succeeded.txt

### PR DESCRIPTION
**Pull request by guifelix**
Create a simpler succeeded message

| Q             | A
| ------------- | ---
| Branch        | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Documented?   | no
| Fixed tickets | no

add another text template to succeeded message

### CODE REVIEW

**Comment by veewee** [comment]
Hello @guifelix ,

Can you also update the documentation?
https://github.com/phpro/grumphp/blob/master/doc/parameters.md
-> ascii

Thanks!

**Comment by guifelix** [comment]
@veewee how do I commit a new file in this same PR? I've never done that

**Comment by jyggen** [comment]
> 
> 
> @veewee how do I commit a new file in this same PR? I've never done that

Commit the changes you want to make to the branch `patch-2` on [your fork](https://github.com/guifelix/grumphp).

**Comment by veewee** [comment]
Thanks for the PRs!

**Pull request merged**
