### PR TITLE
Feature/monolog 2

### PR DESCRIPTION
**Pull request by pimjansen**
| Q             | A
| ------------- | ---
| Branch        | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Documented?   | no
| Fixed tickets | n/a

The PR adds support for Monolog ^2.0

# New Task Checklist:

- [x] Is the README.md file updated?
- [x] Are the dependencies added to the composer.json suggestions?
- [x] Is the doc/tasks.md file updated?
- [x] Are the task parameters documented?
- [x] Is the task registered in the tasks.yml file?
- [x] Does the task contains phpspec tests?
- [x] Is the configuration having logical allowed types?
- [x] Does the task run in the correct context?
- [x] Is the `run()` method readable?
- [x] Is the `run()` method using the configuration correctly?
- [x] Are all CI services returning green?

### CODE REVIEW

**Comment by pimjansen** [comment]
No idea why the builds are failing actually since it seems more like an CI implementation thing?

**Comment by TomPradat** [comment]
I think you should not change the indentation of the `composer.json` file.

Can someone look into the CI which seems broken indeed ?

**Comment by veewee** [comment]
CI is fixed in #644, but I am waiting for a review before I can merge it in. Should have fixed it in a separate PR. The changeset is indeed rather big for one composer version constraint.

**Comment by pimjansen** [comment]
@veewee i updated the file. Updated it default to 2 tab indent instead of 4 what it was.

**Comment by veewee** [comment]
Thanks for the effort! Will merge it soon.

**Comment by pimjansen** [comment]
Thanks 👌🏻

**Pull request merged**
