### PR TITLE
Upgrade PHPUnit

### PR DESCRIPTION
**Pull request by keradus**
| Q             | A
| ------------- | ---
| Branch        | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Documented?   | no
| Fixed tickets | n/a

Brought to you by [PHP CS Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)

### CODE REVIEW

**Comment by keradus** [comment]
thanks for contribution ;)

**Comment by veewee** [comment]
No problem. It seems to fail on PHP 5.6 (with prefer lowest). Can you take a look at it?
https://travis-ci.org/phpro/grumphp/jobs/303537284

**Comment by keradus** [comment]
ha, on my commit it was passing :D

**Comment by keradus** [comment]
fixed.

**Comment by Landerstraeten** [comment]
Thank you @keradus!

**Pull request merged**
