### PR TITLE
Update docs to make it clear that PHP 7 isn't supported yet.

### PR DESCRIPTION
**Pull request by nicrodgers**

### CODE REVIEW

**Comment by jyggen** [comment]
What does not work exactly? I've been running GrumPHP on PHP 7 and above for ages.

**Comment by nicrodgers** [comment]
See https://github.com/phpro/grumphp/issues/482

**Comment by jyggen** [comment]
#482 is about dropping 5.6 support and using PHP 7.0 features in the codebase, but running GrumPHP on PHP 7.0 is already supported (as seen on [Travis](https://travis-ci.org/phpro/grumphp)). So saying "but does not currently support PHP 7" isn't true.

**Comment by nicrodgers** [comment]
Ah, right - my bad then. We recently switched a project that was using grumphp from php 5.6 to php 7, and we were unable to git commit since switching, because grumphp was failing. I checked the issue queue and saw #482, and took that to mean PHP 7 isn't yet supported.

So, i'll close this PR and investigate the bug further, then create an issue for that as necessary.

**Pull request closed without merging**
