### PR TITLE
Add logger + IO classes for easy logging

### PR DESCRIPTION
**Pull request by veewee**
Replacement for #111.

### CODE REVIEW

**Comment by aderuwe** [comment]
:+1: Very elegant solution!

**Comment by llaville** [comment]
@veewee Just one question ! How did you change the logger ? From null to, e.g a file stream

**Comment by veewee** [comment]
This happens in the console application:
https://github.com/phpro/grumphp/pull/114/files#diff-b7ec71ee28477693b4fe918ab314d297R191

The null loger is still available but a stream logger is added to the list of handlers in verbose mode.

**Comment by llaville** [comment]
I see that. I just want to know if there is a solution via yaml config file to change the logger behavior.

E.g: replace null logger by another handler. Currently all goes to the console output. when verbose mode is active

**Comment by llaville** [comment]
I've tried to add in my `grumphp.yml` config file these lines  

```

services:      
  grumphp.logger:
    class: Monolog\Logger
    arguments:
      - 'GrumPHP'
      - ['@grumphp.logger.handler.streamhandler']

  grumphp.logger.handler.streamhandler:
    class: Monolog\Handler\StreamHandler
    public: false
    arguments: [ "/tmp/grump.2.log" ]
```

It works fine. But is it the best pratice ?

**Comment by veewee** [comment]
Yes, that is exactly the idea.

You create the handler you want and register it to the grumphp.logger. By default is will use the nullhandler which won't log anything. If you want to write to a file or some other pllace, you can specify your own handler.

When running the CLI command in verbose mode, the output is also added to the stdout of your terminal, so that the information is displayed in the terminal screen.

**Comment by llaville** [comment]
Thanks for this answer !

**Pull request merged**
