### PR TITLE
Allow ondram/ci-detector ^4.0 upgrade

### PR DESCRIPTION
**Pull request by fbnfgc**
| Q             | A
| ------------- | ---
| Branch        | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? |no
| Documented?   | no
| Fixed tickets |

Allow upgrade of ondram/ci-detector dependency. After reading [the changelog](https://github.com/OndraM/ci-detector/blob/4.1.0/CHANGELOG.md) there is no BC break.

# New Task Checklist:

- [ ] Are the dependencies added to the composer.json suggestions?
- [ ] Is the doc/tasks.md file updated?
- [ ] Are the task parameters documented?
- [ ] Is the task registered in the tasks.yml file?
- [ ] Does the task contains phpunit tests?
- [ ] Is the configuration having logical allowed types?
- [ ] Does the task run in the correct context?
- [ ] Is the `run()` method readable?
- [ ] Is the `run()` method using the configuration correctly?
- [ ] Are all CI services returning green?

### CODE REVIEW

**Comment by veewee** [comment]
Thanks for the PR, it looks good. Maybe even better if we'dd drop 3.X support.
The failing actions don't seem related. I'll have to fix that first.

**Comment by fbnfgc** [comment]
> Thanks for the PR, it looks good. Maybe even better if we'dd drop 3.X support.
> The failing actions don't seem related. I'll have to fix that first.

Thanks @veewee, I've kept the 3.X to avoid a breaking change and a major release, but if you think it's better I can definitely remove the 3.X support :)

I didn't dig into failing actions, but psalm seems unhappy. Here is a

<details>
  <summary>composer packages diff between the last green check (PHP 7.3 composer:v1)</summary>

```diff
2c2
< amphp/amp (v2.5.2)
---
> amphp/amp (v2.6.0)
10,18c10
< doctrine/collections (1.6.7)
< symfony/polyfill-php80 (v1.23.0)
< symfony/process (v5.3.2)
< symfony/polyfill-mbstring (v1.23.0)
< gitonomy/gitlib (v1.2.3)
< psr/log (1.1.4)
< monolog/monolog (2.3.0)
< ondram/ci-detector (3.5.1)
< symfony/polyfill-php81 (v1.23.0)
---
> doctrine/instantiator (1.4.0)
20d11
< symfony/filesystem (v5.3.3)
22c13,23
< symfony/config (v5.3.3)
---
> symfony/yaml (v5.3.6)
> symfony/polyfill-php80 (v1.23.1)
> symfony/finder (v5.3.7)
> symfony/process (v5.3.7)
> psr/event-dispatcher (1.0.0)
> symfony/event-dispatcher-contracts (v2.4.0)
> symfony/event-dispatcher (v5.3.7)
> symfony/polyfill-mbstring (v1.23.1)
> symfony/polyfill-intl-normalizer (v1.23.0)
> symfony/polyfill-intl-grapheme (v1.23.1)
> symfony/string (v5.3.7)
25,26d25
< symfony/dependency-injection (v5.3.3)
< symfony/dotenv (v5.3.0)
28,32c27,49
< symfony/options-resolver (v5.3.0)
< symfony/polyfill-intl-normalizer (v1.23.0)
< symfony/polyfill-intl-grapheme (v1.23.0)
< symfony/string (v5.3.3)
< symfony/console (v5.3.2)
---
> symfony/console (v5.3.7)
> sebastian/recursion-context (4.0.4)
> sebastian/exporter (4.0.3)
> phpspec/php-diff (v1.1.3)
> sebastian/diff (4.0.4)
> sebastian/comparator (4.0.6)
> phpdocumentor/reflection-common (2.2.0)
> webmozart/assert (1.10.0)
> phpdocumentor/type-resolver (1.4.0)
> phpdocumentor/reflection-docblock (5.2.2)
> phpspec/prophecy (1.13.0)
> phpspec/phpspec (7.1.0)
> doctrine/collections (1.6.8)
> gitonomy/gitlib (v1.3.2)
> psr/log (1.1.4)
> monolog/monolog (2.3.2)
> ondram/ci-detector (4.1.0)
> symfony/polyfill-php81 (v1.23.0)
> symfony/filesystem (v5.3.4)
> symfony/config (v5.3.4)
> symfony/dependency-injection (v5.3.7)
> symfony/dotenv (v5.3.7)
> symfony/options-resolver (v5.3.7)
37d53
< sebastian/recursion-context (4.0.4)
41,43d56
< sebastian/exporter (4.0.3)
< sebastian/diff (4.0.4)
< sebastian/comparator (4.0.6)
50,51c63,64
< theseer/tokenizer (1.2.0)
< nikic/php-parser (v4.11.0)
---
> theseer/tokenizer (1.2.1)
> nikic/php-parser (v4.12.0)
56,61d68
< doctrine/instantiator (1.4.0)
< phpdocumentor/reflection-common (2.2.0)
< webmozart/assert (1.10.0)
< phpdocumentor/type-resolver (1.4.0)
< phpdocumentor/reflection-docblock (5.2.2)
< phpspec/prophecy (1.13.0)
63c70
< phar-io/manifest (2.0.1)
---
> phar-io/manifest (2.0.3)
65,66c72,73
< phpunit/phpunit (9.5.6)
< brianium/paratest (v6.3.0)
---
> phpunit/phpunit (9.5.9)
> brianium/paratest (v6.3.1)
68,69c75
< symfony/finder (v5.3.0)
< seld/phar-utils (1.1.1)
---
> seld/phar-utils (1.1.2)
71,72c77,78
< justinrainbow/json-schema (5.2.10)
< composer/xdebug-handler (2.0.1)
---
> justinrainbow/json-schema (5.2.11)
> composer/xdebug-handler (2.0.2)
77,84c83,84
< composer/composer (2.1.3)
< php-parallel-lint/php-parallel-lint (v1.3.0)
< symfony/yaml (v5.3.3)
< psr/event-dispatcher (1.0.0)
< symfony/event-dispatcher-contracts (v2.4.0)
< symfony/event-dispatcher (v5.3.0)
< phpspec/php-diff (v1.1.3)
< phpspec/phpspec (6.3.1)
---
> composer/composer (2.1.6)
> php-parallel-lint/php-parallel-lint (v1.3.1)
```

</details>

Do you have any clue :thinking:?

**Comment by veewee** [comment]
No clue, I'll have to dig in myself as well.
Since doctrine/collections has changed in the diff, it most likely is a change in there that causes the failures.

**Comment by veewee** [comment]
Thanks for your contribution. Fixed the errors in PR #923.

**Pull request merged**
