### PR TITLE
Changes filenames: phpcsfixer, securitychecker

### PR DESCRIPTION
**Pull request by cafferata**
| Q             | A
| ------------- | ---
| Branch        | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Documented?   | yes
| Fixed tickets | 

Expected that the filenames would be the same as there namespaces

### CODE REVIEW

**Comment by veewee** [comment]
Thanks!

**Comment by patkar** [comment]
Aaaaaaaaaaaand it's a BC break if you use redefine php-cs-fixer tasks to have multiple ones :sob: (see https://github.com/phpro/grumphp/issues/309#issuecomment-295249909)

**Comment by cafferata** [comment]
Thanks @patkar for pointing this out.

**Comment by veewee** [comment]
Hi @patkar, 

Thanks for noticing. I've created a BC break label and will try to review these kind of BC breaks as well. 
Let's hope that this is sufficient to avoid BC breaks as much as possible. Do note that we are in the 0.x phase, so there might be some additional breaks in the future.

**Comment by patkar** [comment]
Of course it's 0.x so I'm aware of bigger changes. And also this is a subtile one, because is this an extension point or not.. 

And it was easy enough and fastly fixed in our conventions checker. Gladfully we did that in a central repo and not every project created this config on their own. I only wanted to point that out for further considerations/issues/PRs ;)

**Pull request merged**
