### PR TITLE
All security checkers you ever needed

### PR DESCRIPTION
**Pull request by veewee**
| Q             | A
| ------------- | ---
| Branch        | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Documented?   | yes
| Fixed tickets | #865, #870, #871

This PR adds support for 3 new security checkers in a BC safe way:

- fabpot-local
- symfony security:check
- enligthn

### CODE REVIEW

**Comment by veewee** [comment]
@paras-malhotra / @JeppeKnockaert /  : I provided an alternative solution. Can you take a look at this approach? Thanks!

**Comment by paras-malhotra** [comment]
Looking great @veewee! 👍

Gotta admit the title of this PR is humorous 😄

**Comment by cerw** [comment]
Please merge, we need it :) thanks

**Comment by veewee** [comment]
It's coming up today @cerw ... Give me some time. Thanks for the patience!

**Comment by cerw** [comment]
@veewee Amazing! thanks

**Pull request merged**
