### PR TITLE
Add docker-compose support

### PR DESCRIPTION
**Pull request by jeckel**
| Q             | A
| ------------- | ---
| Branch        | master for features and deprecations
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Documented?   | yes
| Fixed tickets | #152 

Add `docker-compose` support:
- add new hooks template dedicated to docker-compose
- add new parameter `DOCKER_COMPOSE_CONTAINER` to specify in which container the hooks should be executed
- update corresponding documentation

### CODE REVIEW

**Comment by jeckel** [comment]
I wonder if it's required to add another template for cases when you need to run in a **docker** container not defined in a `docker-compose` file. Maybe by specifying a docker image name.

**Comment by veewee** [comment]
Hi @jeckel ,

It looks nice, thanks!
You might want to make the docker-compose command configurable as well. That way it could also be used with regular docker I guess.
We're also making the exec part configurable in https://github.com/phpro/grumphp/pull/618.

**Comment by jeckel** [comment]
I just looked at the other PR, as I understand it, it will make this one as duplicate.

Customizing the exec part might solve the problem in most docker and docker-compose situations.

I'll try to test it with my current setup

**Comment by veewee** [comment]
Indeed, now that you mention it this PR might be obsolete.
If so, we'll have to document various use cases of the `EXEC_GRUMPHP_COMMAND` param.
(E.g.: php, php72, docker, docker-compose, ...)

**Comment by divined** [comment]
@jeckel Can you merge it to your master branch and create the tag for it?
The community can't test it:
composer require jeckel/grumphp:dev-docker-compose don't work (

**Comment by jeckel** [comment]
Done : https://github.com/jeckel/grumphp/releases/tag/v0.15.1

**Comment by jeckel** [comment]
> @jeckel Can you merge it to your master branch and create the tag for it?
> The community can't test it:
> composer require jeckel/grumphp:dev-docker-compose don't work (

This fork is not registered on packagist, you need to specify the repository in your `composer.json` file

```json
"repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/jeckel/grumphp"
    }
  ],
```

**Comment by veewee** [comment]
Will be fixed through #615

**Pull request closed without merging**
