### PR TITLE
CS: fix PSR2 violations

### PR DESCRIPTION
**Pull request by keradus**
| Q             | A
| ------------- | ---
| Branch        | master for features and deprecations
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Documented?   | no
| Fixed tickets | no

Fix PSR2 violations. Mostly lack of methods visibility, but also placement of braces and method arguments.

Brought to you by [PHP CS Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)

### CODE REVIEW

**Comment by Landerstraeten** [comment]
@keradus, why would you add public visibility (explicit) to the tests?
See https://github.com/phpspec/phpspec/pull/590#issuecomment-67995169

**Comment by keradus** [comment]
because most of devs like having the visibility.
and even if visibility keyword is forgot, php still adds `public` under the hood.
I would say no more than was said in thread - psr2 or not.
If one wants to have language agnostic spec - go in language agnostic spec framework, like in behat scenarios are language agnostic. if we go with PHP, would be nice to follow good practices.

If you don't want to have them - cool, just close the PR ;) no bad feelings ;)

**Comment by keradus** [comment]
please make a decision, either close or ask me to rebase ;)

**Comment by Landerstraeten** [comment]
Thanks for the PR @keradus! But I don't see the added value of the public visibility for tests

**Comment by keradus** [comment]
sad for me, but totally understandable :+1:

**Pull request closed without merging**
