### PR TITLE
PSR-0 is so 2010

### PR DESCRIPTION
**Pull request by Bilge**
| Q             | A
| ------------- | ---
| Branch        | master 
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Documented?   | no
| Fixed tickets | n/a

[PSR-0 has been deprecated since 2014-10-21](http://www.php-fig.org/psr/psr-0/). With the new PSR-4 structure we can enjoy eliminating redundant folders in the hierarchy that only contain one other embedded directory within them.

### CODE REVIEW

**Comment by veewee** [comment]
Thanks for your work this weekend, I really appreciate it!
I did not know they deprecated it.
Can you rebase your changes to get this one merged in?

**Comment by Bilge** [comment]
I will redo this PR later this evening. I think there are too many
conflicts to rebase.

**Comment by Bilge** [comment]
@veewee All done.

**Comment by veewee** [comment]
Thanks! I'll keep this one open for a while until the open PRs are finished. This way it won't be blocking other peoples code.

**Comment by Bilge** [comment]
That's not a good idea. This will conflict with their PRs but the reverse
is also true. It makes sense to merge whichever PR is ready whether it is
mine or theirs because nothing is gained by waiting; if that was the case
git would be poorly designed, but it is not.

As it turns out, all I had to do was rebase after all; git figured out the
rest, therefore that is all they will have to do. Hence you should merge
whichever PR is ready instead of waiting on unrelated PRs that haven't been
updated in months as you run the risk that I may be unavailable to update
this PR by that time.

**Comment by Bilge** [comment]
That's not a good idea. This will conflict with their PRs but the reverse
is also true. It makes sense to merge whichever PR is ready whether it is
mine or theirs because nothing is gained by waiting; if that was the case
git would be poorly designed, but it is not.

As it turns out, all I had to do was rebase after all; git figured out the
rest, therefore that is all they will have to do. Hence you should merge
whichever PR is ready instead of waiting on unrelated PRs that haven't been
updated in months as you run the risk that I may be unavailable to update
this PR by that time.

On 17 Jan 2017 07:52, "Toon Verwerft" <notifications@github.com> wrote:

Thanks! I'll keep this one open for a while until the open PRs are
finished. This way it won't be blocking other peoples code.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/phpro/grumphp/pull/274#issuecomment-273044740>, or mute
the thread

**Comment by Bilge** [comment]
Look, there's conflicting files again already.

**Comment by veewee** [comment]
Point taken :)

**Comment by Bilge** [comment]
So now what do we do? This is most perplexing, isn't it?

**Comment by Bilge** [comment]
@veewee I rebased again in the hopes that you will merge this PR nextish.

**Comment by veewee** [comment]
Hi @Bilge,

No worries, this will be the next merged PR. I am quite busy this week, so this will be something for next week. I'll also try to provide some basic commands for rebasing the open PRs against the code in this one with some additional tips to make it as non-blocking as possible for the other contributors.

**Comment by Bilge** [comment]
If you're already committed to merging this next, what is gained by waiting
any longer?

The command is `git rebase upstream/master`. It's that simple.

**Comment by veewee** [comment]
Finally merged ... Thanks again!

**Pull request merged**
