### PR TITLE
Add PhpCpd task

### PR DESCRIPTION
**Pull request by jyggen**
| Q             | A
| ------------- | ---
| Branch        | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documented?   | yes
| Fixed tickets | #192

# New Task Checklist:

- [x] Is the README.md file updated?
- [x] Are the dependencies added to the composer.json suggestions?
- [x] Is the doc/tasks.md file updated?
- [x] Are the task parameters documented?
- [x] Is the task registered in the tasks.yml file?
- [x] Does the task contains phpspec tests?
- [x] Is the configuration having logical allowed types?
- [x] Does the task run in the correct context?
- [x] Is the `run()` method readable?
- [x] Is the `run()` method using the configuration correctly?
- [x] Are all CI services returning green?

### CODE REVIEW

**Comment by veewee** [comment]
Hi @jyggen,

It looks pretty good! Can you also add the `exclude` option?
Normally we wouldn't like to run this tools on spec or test files etc.

Thanks!

**Comment by jyggen** [comment]
I tried adding that option at first but the problem I'm facing with both `--exclude` and `--names-exclude` is that they only seem to work on sub-directories and files within the analyzed location, and since GrumPHP gives `phpcpd` a list of exact file locations those options seem to be simply ignored. 

Running it on a specific file:
```shell
$ ./vendor/bin/phpcpd --exclude=spec --exclude=vendor spec/GrumPHP/Task/PhpCsFixerSpec.php

phpcpd 2.0.4 by Sebastian Bergmann.

Found 1 exact clones with 20 duplicated lines in 1 files:

  -	/path/to/grumphp/spec/GrumPHP/Task/PhpCsFixerSpec.php:87-107
 	/path/to/grumphp/spec/GrumPHP/Task/PhpCsFixerSpec.php:113-133

12.90% duplicated lines out of 155 total lines of code.

Time: 30 ms, Memory: 4.00MB
```

Running it on the root folder:
```shell
$ ./vendor/bin/phpcpd --exclude=spec --exclude=vendor .
phpcpd 2.0.4 by Sebastian Bergmann.

0.00% duplicated lines out of 8668 total lines of code.

Time: 79 ms, Memory: 8.00MB
```

However; I've pushed an implementation of an `exclude` option using `FilesCollection` (with some minor optimizations) instead of what's built into `phpcpd`. Does it seem like a good alternative or should I simply leave out an `exclude` option for now?

**Comment by veewee** [comment]
Does the tool only detect copy-pasted code between the files you add as a parameter to the command? So for example: If I commit `class1.php` which contains duplicate code from `class2.php`, it won't detect the duplicate code since it is only checking `class1.php`?
Maybe it's better to let the tool run on the complete codebase instead of only on the committed files?

**Comment by jyggen** [comment]
Correct. It only detect copy-pasted code between files added as parameters, so it's probably better to let the tool run on the complete codebase. Any pointers on how to make it do that?

```shell
$ ./vendor/bin/phpcpd spec/GrumPHP/Task/PhpCsFixerSpec.php
phpcpd 2.0.4 by Sebastian Bergmann.

Found 1 exact clones with 20 duplicated lines in 1 files:

  -	/path/to/grumphp/spec/GrumPHP/Task/PhpCsFixerSpec.php:87-107
 	/path/to/grumphp/spec/GrumPHP/Task/PhpCsFixerSpec.php:113-133

12.90% duplicated lines out of 155 total lines of code.

Time: 31 ms, Memory: 4.00MB
```

```shell
$ ./vendor/bin/phpcpd spec/GrumPHP/Task/
phpcpd 2.0.4 by Sebastian Bergmann.

Found 3 exact clones with 120 duplicated lines in 2 files:

  -	/path/to/grumphp/spec/GrumPHP/Task/PhpCsFixerSpec.php:87-107
 	/path/to/grumphp/spec/GrumPHP/Task/PhpCsFixerSpec.php:113-133

  -	/path/to/grumphp/spec/GrumPHP/Task/PhpCsFixerSpec.php:55-87
 	/path/to/grumphp/spec/GrumPHP/Task/PhpCsFixerV2Spec.php:57-89

  -	/path/to/grumphp/spec/GrumPHP/Task/PhpCsFixerSpec.php:86-154
 	/path/to/grumphp/spec/GrumPHP/Task/PhpCsFixerV2Spec.php:88-156

3.61% duplicated lines out of 3327 total lines of code.

Time: 80 ms, Memory: 6.00MB
```

**Comment by veewee** [comment]
Maybe it's best to let the tool run in the current working directory by specifying the source `.` or `getcwd()`?
This way, the tool will run on the full codebase and you can specify which directories / files you want to exclude for the phpcpd task.
Another option is to run it in the `$this->grumPHP->getGitDir();` folder, but this might be overkill in projects with a nested structure.

**Comment by jyggen** [comment]
@veewee: Done.  I added `vendor` as the default exclude since I doubt anyone will ever want to find copy-pasted code in there.

**Comment by veewee** [comment]
Hi @jyggen,

Now that I see the code, I was thinking in making it configurable.
Instead of using the `getcwd()` method, we could read it from `$config['directory']` or something like that. By default the value is set to `.` which means it will load the current directory.
This way it is easy to configure it to scan e.g. the `src` folder, but exclude specific folders like e.g. `src/Resources`. What do you think about this feature?

**Comment by jyggen** [comment]
@veewee: Sounds good to me. Implemented :)

**Comment by veewee** [comment]
Super! :) I've merged it.

**Pull request merged**
