### PR TITLE
TwigCs - allocine/twigcs is abandoned. Changed to friendsoftwig/twigcs

### PR DESCRIPTION
**Pull request by truls1502**
| Q             | A
| ------------- | ---
| Branch        | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Documented?   | no

Updated TwigCs from allocine/twigcs to friendsoftwig/twigcs when [allocine/twigcs is abandoned and no longer maintained](https://packagist.org/packages/allocine/twigcs).

# New Task Checklist:

- [ ] Is the README.md file updated?
- [ ] Are the dependencies added to the composer.json suggestions?
- [ ] Is the doc/tasks.md file updated?
- [ ] Are the task parameters documented?
- [ ] Is the task registered in the tasks.yml file?
- [ ] Does the task contains phpspec tests?
- [ ] Is the configuration having logical allowed types?
- [ ] Does the task run in the correct context?
- [ ] Is the `run()` method readable?
- [ ] Is the `run()` method using the configuration correctly?
- [ ] Are all CI services returning green?

### CODE REVIEW

**Comment by veewee** [comment]
Thanks for the PR!

**Comment by drupol** [comment]
We should add a "exclude" folders option so it doesn't check in the `vendor` directory, but this must be done in https://github.com/friendsoftwig/twigcs directly I think.

**Comment by oallain** [comment]
> We should add a "exclude" folders option so it doesn't check in the `vendor` directory, but this must be done in https://github.com/friendsoftwig/twigcs directly I think.

Hello, @drupol 
I had a new PR in TwigCs for that :wink:  

Hoping it will help you.

**Comment by drupol** [comment]
Nice ! Link ?

**Comment by truls1502** [comment]
@oallain - is this PR https://github.com/friendsoftwig/twigcs/pull/81?

**Comment by oallain** [comment]
Yes, it's that.

I'll create a new PR here for integrate it.

**Pull request merged**
