### PR TITLE
fabpot-cs-fixer is abandoned, use the friendsofphp version instead

### PR DESCRIPTION
**Pull request by johnhout**
| Q             | A
| ------------- | ---
| Branch        | master
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documented?  | no

### CODE REVIEW

**Comment by veewee** [comment]
Hi @johnhout,

Thanks for the PR. 
Can you add a comma to the end of the line so that the tests pass?

**Comment by veewee** [comment]
There is also a reference in the suggest block:

```
"fabpot/php-cs-fixer": "Lets GrumPHP automatically fix your codestyle.",
```

**Comment by johnhout** [comment]
Sorry, Should have double checked ;)

**Comment by veewee** [comment]
Thanks!

**Pull request merged**
