### PR TITLE
PhpCs Specifying an Encoding

### PR DESCRIPTION
**Pull request by TheRatG**
| Q             | A
| ------------- | ---
| Branch        | master for features and deprecations
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documented?   | yes
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any

There is encoding param support for phpcs task.

### CODE REVIEW

**Comment by veewee** [comment]
Thanks for the PR. It looks good!
Can you update the task spec file?

**Comment by TheRatG** [comment]
Done. I was inattentive.
Thanks for your application, it is very useful.

**Comment by whyte624** [comment]
👍

**Comment by veewee** [comment]
Thanks!

**Pull request merged**
