### PR TITLE
Only show project files when project is in subfolder

### PR DESCRIPTION
**Pull request by veewee**
| Q             | A
| ------------- | ---
| Branch        | master
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | yes
| Deprecations? | no
| Documented?   | 
| Fixed tickets | #607, #592

This PR will fix invalid files when using grumphp.yml + composer.jshon in a single subdirectory inside git.

For example: ./project

### CODE REVIEW

**Comment by mattheo-geoffray** [comment]
@veewee Hi, do you when the next release is planned?

**Comment by veewee** [comment]
Hi @mattheo-geoffray,

Sadly I discovered some broken scenario's when testing out [conventions](https://github.com/phpro/grumphp/blob/master/doc/conventions.md).
There are still some other scenario's well want to cover before releasing, since they will break BC.
In the meantime, you can check out master and use that one to verify if everything works for you.
You can also track progress in #644, but I am afraid I won't be able to work on that one very frequently.

**Comment by mattheo-geoffray** [comment]
@veewee Hi!
Oh OK no problem I will work with that one until it can be a stable release!   
Thank you for the work! 🙂

**Comment by mattheo-geoffray** [comment]
Hi @veewee !
Do you have an idea for the release date of this PR?  
Thanks!

**Comment by veewee** [comment]
Not yet, first have to find time to finish the pr above.

**Pull request merged**
